-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero

local fireLimit = 20
local fireDelay = 0.1

local timeFire = 0

if game.PlaceId == 1112836482 then
    while timeFire < fireLimit do
        for k, v in pairs(game:GetService("Workspace"):GetChildren()) do
            if (tostring(v) == "Timey") then
                local A_1 = game:GetService("Workspace").Timey:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Timey:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "Gibbs") then
                local A_1 = game:GetService("Workspace").Gibbs:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Gibbs:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "Police") then
                local A_1 = game:GetService("Workspace").Police:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Police:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "Sedan") then
                local A_1 = game:GetService("Workspace").Sedan:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Sedan:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "Jalopy") then
                local A_1 = game:GetService("Workspace").Jalopy:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Jalopy:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "ATV") then
                local A_1 = game:GetService("Workspace").ATV:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").ATV:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "Van") then
                local A_1 = game:GetService("Workspace").Van:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Van:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "Humvee") then
                local A_1 = game:GetService("Workspace").Humvee:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Humvee:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "SniperVan") then
                local A_1 = game:GetService("Workspace").SniperVan:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").SniperVan:FindFirstChild("Car").VehicleSeat.Honk
                    Event:FireServer(A_1)
                end
                continue
            elseif (tostring(v) == "Rover") then
                local A_1 = game:GetService("Workspace").Rover:FindFirstChild("Car")
                if A_1 ~= nil and A_1:FindFirstChild("VehicleSeat") then
                    local Event = game:GetService("Workspace").Rover:FindFirstChild("Car"):FindFirstChild("VehicleSeat").Honk
                    Event:FireServer(A_1)
                end
                continue
            end
        end
        timeFire += 1
        task.wait(fireDelay)
    end
else
    print("Game not supported!, the game is : https://www.roblox.com/games/1112836482/Car-Suspension-Test-Voice-Chat")
end